---
title: "Advanced Modeling"
author: "Cam Smithers"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Necessary Packages

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(rsample)
library(caret)
library(vip)
library(ROCR)
library(nnet)
```

### Necessary Data Sets

```{r}
setwd('/Users/camsmithers/Desktop/Camalytics/NBA')
teamvisdata <- readRDS('Data-NBA/Current/teamvisdata.rds')
teamvisdata_fixed <- na.omit(teamvisdata) %>%
    mutate(
        team = as.factor(team),
        opponent = as.factor(opponent),
        season = as.factor(season))
```

## Linear Regression Model Testing: Player Statistics

------------------------------------------------------------------------

## Logistic Regression Model Testing: Binary Game Outcome

```{r}
winbinary_split <- initial_split(teamvisdata_fixed, prop=.75, strat='twoleveloc')
winbinary_train <- training(winbinary_split)
winbinary_test <- testing(winbinary_split)
```

For the models I started by adding all the variables that I wanted and deciding which ones I wanted to remove to see how the accuracy changes.

```{r}
winbinary_1 <- train(
    twoleveloc ~ roll_offrating + roll_defrating + team + homeaway + 
        vorp_bpa + roll_three_par + roll_ftar + roll_ast_pct,
    data=teamvisdata_fixed,
    method='glm',
    family='binomial',
    trControl=trainControl(method='cv', number=10))
winbinary_2 <- train(
    twoleveloc ~ roll_offrating + roll_defrating,
    data=teamvisdata_fixed,
    method='glm',
    family='binomial',
    trControl=trainControl(method='cv', number=10))
winbinary_3 <- train(
    twoleveloc ~ roll_offrating + opponent,
    data=teamvisdata_fixed,
    method='glm',
    family='binomial',
    trControl=trainControl(method='cv', number=10))
winbinary_4 <- train(
    twoleveloc ~ homeaway,
    data=teamvisdata_fixed,
    method='glm',
    family='binomial',
    trControl=trainControl(method='cv', number=10))
```

This will give the me summary statistics of the models' accuracy.

```{r}
summary(
    resamples(
        list(
            model1=winbinary_1,
            model2=winbinary_2,
            model3=winbinary_3,
            model4=winbinary_4
        )
    )
)$statistics$Accuracy
```

### ROC Curve for Logistic Regression Models

Creating a plot to show the False Positive vs. True Positive Accuracy.

```{r}
model1_prob <- predict(winbinary_1, winbinary_train, type='prob')$Win
perf1 <- prediction(model1_prob, winbinary_train$twoleveloc) %>%
    performance(measure='tpr', x.measure='fpr')

model2_prob <- predict(winbinary_2, winbinary_train, type='prob')$Win
perf2 <- prediction(model2_prob, winbinary_train$twoleveloc) %>%
    performance(measure='tpr', x.measure='fpr')

model3_prob <- predict(winbinary_3, winbinary_train, type='prob')$Win
perf3 <- prediction(model3_prob, winbinary_train$twoleveloc) %>%
    performance(measure='tpr', x.measure='fpr')

model4_prob <- predict(winbinary_4, winbinary_train, type='prob')$Win
perf4 <- prediction(model4_prob, winbinary_train$twoleveloc) %>%
    performance(measure='tpr', x.measure='fpr')

plot(perf1, col='cornflowerblue', lty=1)
plot(perf2, add=TRUE, col='magenta2', lty=2)
plot(perf3, add=TRUE, col='gold2', lty=2)
plot(perf4, add=TRUE, col='forestgreen', lty=2)
legend(0.6, 0.3, legend=c('Full Model',
                          'Net Rating',
                          'Offensive Rating w/ Opponent',
                         'Defensive Rating w/ Team'),
       col=c('cornflowerblue', 'magenta2', 'gold2', 'forestgreen'),
       lty=2:1, cex=0.6)
```

------------------------------------------------------------------------

## Multinomial Regression Testing: Outcome w/ Magnitude

```{r}

```
