---
title: "Modeling"
author: "Cam Smithers"
date: "`r Sys.Date()`"
output: pdf_document
---

# NBA Statistical Modeling & Prediction

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Necessary Packages

```{r}
library(tidyverse)
library(rsample)
library(caret)
library(vip)
library(ROCR)
library(nnet)
```

Necessary Data Sets

```{r}
source("inR/Functions.R")

team_season_stats <- readRDS(
    "Data-NBA/team_season_stats.rds")

player_regseason_stats <- readRDS(
    "Data-NBA/plyr_regsn_stats.rds")

team_box_scores <- readRDS(
    "Data-NBA/team_box_scores_updated.rds")
```

## Pre-Analysis Cleaning

```{r}
team_box_scores_2 <- team_box_scores %>%
    mutate(
        true_oreb_pct = round((oreb_pct * treb_pct) / 100, 1),
        true_dreb_pct = round((dreb_pct * treb_pct) / 100, 1))

opp_box_data <- team_box_scores %>%
    select(gamedate, team, pts, fg_pct, threefg_pct, efg_pct) %>%
    rename_with( ~paste0("opp_", .x), .cols = -c("gamedate", "team"))

team_box_scores_3 <- team_box_scores_2 %>%
    left_join(opp_box_data, by = c("gamedate", "opponent"="team")) %>%
    mutate(
        win = if_else(offrating > defrating, 1, 0),
        point_diff = pts - opp_pts,
        outcome_margin = case_when(
            point_diff >= 10 ~ 0,
            point_diff < 10 & point_diff > 0 ~ 1,
            point_diff < 0 & point_diff > -10 ~ 2,
            point_diff <= -10 ~ 3),
        win = factor(win,
                     levels = c(0, 1),
                     labels = c("Loss", "Win")),
        outcome_margin = factor(outcome_margin,
                                levels = c(0, 1, 2, 3),
                                labels = c("Blowout Win",
                                           "Close Win",
                                           "Close Loss",
                                           "Blowout Loss"))) %>%
    group_by(team, season) %>%
    mutate(avg_outcome_margin = round(mean(point_diff), 2))
```

## Logistic Regression Model Testing

```{r}
win_split <- initial_split(team_box_scores_3, prop = .65, strata = "win")
win_train <- training(win_split)
win_test <- testing(win_split)
```

```{r}
win_one <- train(
    win ~ offrating,
    data = team_box_scores_3,
    method = "glm",
    family = "binomial",
    trControl = trainControl(method = "cv", number = 10))
win_two <- train(
    win ~ defrating,
    data = team_box_scores_3,
    method = "glm",
    family = "binomial",
    trControl = trainControl(method = "cv", number = 10))
win_three <- train(
    win ~ threefg_pct + ftar,
    data = team_box_scores_3,
    method = "glm",
    family = "binomial",
    trControl = trainControl(method = "cv", number = 10))
win_four <- train(
    win ~ true_oreb_pct + true_dreb_pct,
    data = team_box_scores_3,
    method = "glm",
    family = "binomial",
    trControl = trainControl(method = "cv", number = 10))
win_five <- train(
    win ~ defrating + threefg_pct + ftar + true_oreb_pct + true_dreb_pct,
    data = team_box_scores_3,
    method = "glm",
    family = "binomial",
    trControl = trainControl(method = "cv", number = 10))
```

```{r}
summary(
    resamples(
        list(
            model1 = win_one,
            model2 = win_two,
            model3 = win_three,
            model4 = win_four,
            model5 = win_five
        )
    )
)$statistics$Accuracy
```

### ROC Curve for Logistic Regression Models (Game Outcome Win/Loss)

```{r}
model1_prob <- predict(win_one, win_train, type = "prob")$Win
perf1 <- prediction(model1_prob, win_train$win) %>%
    performance(measure = "tpr", x.measure = "fpr")

model2_prob <- predict(win_two, win_train, type = "prob")$Win
perf2 <- prediction(model2_prob, win_train$win) %>%
    performance(measure = "tpr", x.measure = "fpr")

model3_prob <- predict(win_three, win_train, type = "prob")$Win
perf3 <- prediction(model3_prob, win_train$win) %>%
    performance(measure = "tpr", x.measure = "fpr")

model4_prob <- predict(win_four, win_train, type = "prob")$Win
perf4 <- prediction(model4_prob, win_train$win) %>%
    performance(measure = "tpr", x.measure = "fpr")

model5_prob <- predict(win_five, win_train, type = "prob")$Win
perf5 <- prediction(model5_prob, win_train$win) %>%
    performance(measure = "tpr", x.measure = "fpr")

plot(perf1, col = "black", lty = 1)
plot(perf2, add = TRUE, col = "cornflowerblue", lty = 2)
plot(perf3, add = TRUE, col = "red3", lty = 2)
plot(perf4, add = TRUE, col = "magenta2", lty = 2)
plot(perf5, add = TRUE, col = "gold2", lty = 2)
legend(0.8, 0.4, legend = c("win_one", "win_two", "win_three", "win_four", "win_five"),
       col = c("black", "cornflowerblue", "red3", "magenta2", "gold2"), lty = 2:1, cex = 0.6)
```

------------------------------------------------------------------------

```{r}
outcome_margin_split <- initial_split(team_box_scores_3, prop = .65, strata = "outcome_margin")
outcome_margin_train <- training(outcome_margin_split)
outcome_margin_test <- testing(outcome_margin_split)
```

```{r}
outcome_margin_one <- train(
    outcome_margin ~ offrating + avg_outcome_margin,
    data = team_box_scores_3,
    method = "multinom",
#    family = "binomial",
    trControl = trainControl(method = "cv", number = 10))
outcome_margin_two <- train(
    outcome_margin ~ defrating + avg_outcome_margin,
    data = team_box_scores_3,
    method = "multinom",
#    family = "binomial",
    trControl = trainControl(method = "cv", number = 10))
outcome_margin_three <- train(
    outcome_margin ~ threefg_pct + ftar + avg_outcome_margin,
    data = team_box_scores_3,
    method = "multinom",
#    family = "binomial",
    trControl = trainControl(method = "cv", number = 10))
outcome_margin_four <- train(
    outcome_margin ~ true_oreb_pct + true_dreb_pct + avg_outcome_margin,
    data = team_box_scores_3,
    method = "multinom",
#    family = "binomial",
    trControl = trainControl(method = "cv", number = 10))
outcome_margin_five <- train(
    outcome_margin ~ defrating + threefg_pct + ftar + 
        true_oreb_pct + true_dreb_pct + avg_outcome_margin,
    data = team_box_scores_3,
    method = "multinom",
#    family = "binomial",
    trControl = trainControl(method = "cv", number = 10))
```

```{r}
summary(
    resamples(
        list(
            model6 = outcome_margin_one,
            model7 = outcome_margin_two,
            model8 = outcome_margin_three,
            model9 = outcome_margin_four,
            model10 = outcome_margin_five
        )
    )
)$statistics$Accuracy
```
